# Generated by Django 2.2.6 on 2019-11-03 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_usermodel_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='movie',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
