# Generated by Django 2.2.7 on 2019-11-17 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usermodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='join_date',
        ),
    ]
