# Generated by Django 2.2.7 on 2019-11-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usermodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.CharField(default='NULL', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_name',
            field=models.CharField(default='NULL', max_length=100, unique=True),
        ),
    ]
