# Generated by Django 2.2.6 on 2019-10-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='/images/pika.jpeg', upload_to=''),
        ),
    ]
