# Generated by Django 2.2.6 on 2019-10-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='/images/pika.jpeg', upload_to='images/'),
        ),
    ]
