# Generated by Django 2.2.6 on 2019-10-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_review_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='link',
            field=models.SlugField(default='NULL', max_length=100),
        ),
    ]
