# Generated by Django 2.2.6 on 2019-11-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_movie_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='id',
        ),
        migrations.AlterField(
            model_name='review',
            name='critic',
            field=models.CharField(default='NULL', max_length=50, primary_key=True, serialize=False),
        ),
    ]
