# Generated by Django 2.2.6 on 2019-11-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20191101_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, default='media/images/SW1.jpg', upload_to='images'),
        ),
    ]
