# Generated by Django 2.2.6 on 2019-11-13 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20191110_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='critic',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(default='NULL', max_length=1000, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('critic', models.CharField(default='NULL', max_length=50, primary_key=True, serialize=False)),
                ('review', models.TextField(default='NULL', max_length=1000)),
                ('movie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='movies.Movie')),
            ],
        ),
    ]
