# Generated by Django 2.2.6 on 2019-11-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20191113_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='critic',
            field=models.CharField(default='NULL', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(default='NULL', max_length=1000),
        ),
    ]
