# Generated by Django 2.2.6 on 2019-11-20 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20191120_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('critic', models.CharField(default='NULL', max_length=50)),
                ('review', models.TextField(default='NULL', max_length=1000)),
                ('movie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='movies.Movie')),
            ],
        ),
    ]
