# Generated by Django 2.2.6 on 2019-11-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_review2_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='aggScore',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='reviews',
            field=models.FloatField(default=0),
        ),
    ]
