# Generated by Django 2.2.7 on 2019-11-28 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0010_auto_20191120_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='review2',
            name='review_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review2',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
