# Generated by Django 2.2.7 on 2019-11-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20191127_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='critc_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='critic_aggScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='user_aggScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='user_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
