# Generated by Django 2.2.7 on 2019-11-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20191129_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='critic_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='user_score',
            field=models.FloatField(default=0),
        ),
    ]
