# Generated by Django 2.2.7 on 2019-11-29 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20191129_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='critc_reviews',
            new_name='critic_reviews',
        ),
    ]
