# Generated by Django 2.2.6 on 2019-12-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_auto_20191129_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='inTheater',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='link',
            field=models.SlugField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='releaseDate',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='star',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='studio',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
